### ISSUE TITLE
HTTPHeaderTextMapCarrier -> HTTPHeadersCarrier

### ISSUE THREAD

**Issue by bsr203** [bg451/opentracing-example#1]
HI thanks for the example. Found an issue

```
undefined: "github.com/opentracing/opentracing-go".HTTPHeaderTextMapCarrier
```

It works fine renaming `HTTPHeaderTextMapCarrier` -> `HTTPHeadersCarrier`

**Comment by bg451** [comment]
Thanks for catching this, opentracing recently made HTTPHeadersCarrier a default carrier type. Would you mind submitting a PR with the change? Thanks!

**Comment by bsr203** [comment]
:-) ok will do..

**Comment by bsr203** [comment]
Is there any gitter/slack/discord channel are you available. I see you contributed to appstats and opentracing extensively and have some questions to know what to use when. Bit overwhelmed with the choices. thanks. Or can I send a mail instead?

**Comment by bsr203** [comment]
https://github.com/bg451/opentracing-example/pull/2

**Comment by bg451** [comment]
@bsr203 I'd be more than happy to answer any questions. We have a gitter channel on https://gitter.im/opentracing/public, or if you want to email, shoot me a message at bg@lightstep.com
